### ISSUE TITLE
exception_access_violation

### ISSUE THREAD

**Issue by TheSainEyereg** [requizm/cs2d_1011v#1]
I compiled this cheat and after trying to inject I got this error. Configuration of the project: Release x86. The injection was performed via Process Hacker 2 and Manual Map Injector. 
![image](https://user-images.githubusercontent.com/37226226/82092256-98a60500-9701-11ea-88a5-699f4f34ab8e.png) 
![image](https://user-images.githubusercontent.com/37226226/82092300-af4c5c00-9701-11ea-9811-19dc042ceff2.png)

What should I do?

**Comment by requizm** [comment]
> I compiled this cheat and after trying to inject I got this error. Configuration of the project: Release x86. The injection was performed via Process Hacker 2 and Manual Map Injector.
> ![image](https://user-images.githubusercontent.com/37226226/82092256-98a60500-9701-11ea-88a5-699f4f34ab8e.png)
> ![image](https://user-images.githubusercontent.com/37226226/82092300-af4c5c00-9701-11ea-9811-19dc042ceff2.png)
> 
> What should I do?

Manual mapping could be problem. Try to LoadLibrary. You can use GH Injector.

**Comment by TheSainEyereg** [comment]
I tried, same

**Comment by requizm** [comment]
> I tried, same

Are you playing on Steam? Maybe Steam build is different from original. I'm using on original(non-steam) build.

**Comment by TheSainEyereg** [comment]
> Are you playing on Steam? Maybe Steam build is different from original. I'm using on original(non-steam) build. 

Sorry for the long silence, the bug disappeared when I switched to a version not from Steam. Thanks for the help
